
"""
Task repository.

Stores tasks generated by the Agentic workflow engine.
"""

from __future__ import annotations

from typing import Any

from backend.app.database.client import (
    SupabaseDatabase,
    get_database,
)


class TaskRepository:
    """Database operations for agent tasks."""

    TABLE = "tasks"

    VALID_STATUSES = {
        "pending",
        "running",
        "completed",
        "failed",
        "cancelled",
        "waiting_approval",
    }

    def __init__(
        self,
        database: SupabaseDatabase | None = None,
    ):
        self.database = database or get_database()

    def create(
        self,
        user_id: str,
        task_type: str,
        description: str,
        conversation_id: str | None = None,
        parent_task_id: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create an agent task."""

        if not user_id:
            raise ValueError(
                "user_id is required."
            )

        if not task_type:
            raise ValueError(
                "task_type is required."
            )

        if not description or not description.strip():
            raise ValueError(
                "description cannot be empty."
            )

        payload: dict[str, Any] = {
            "user_id": user_id,
            "task_type": task_type,
            "description": description,
            "status": "pending",
        }

        if conversation_id:
            payload["conversation_id"] = conversation_id

        if parent_task_id:
            payload["parent_task_id"] = parent_task_id

        if metadata is not None:
            payload["metadata"] = metadata

        response = (
            self.database
            .table(self.TABLE)
            .insert(payload)
            .execute()
        )

        if not response.data:
            raise RuntimeError(
                "Failed to create task."
            )

        return response.data[0]

    def get(
        self,
        task_id: str,
    ) -> dict[str, Any] | None:
        """Get a task."""

        if not task_id:
            raise ValueError(
                "task_id is required."
            )

        response = (
            self.database
            .table(self.TABLE)
            .select("*")
            .eq("id", task_id)
            .limit(1)
            .execute()
        )

        return (
            response.data[0]
            if response.data
            else None
        )

    def update_status(
        self,
        task_id: str,
        status: str,
        error_message: str | None = None,
    ) -> dict[str, Any] | None:
        """Update task status."""

        if not task_id:
            raise ValueError(
                "task_id is required."
            )

        if status not in self.VALID_STATUSES:
            raise ValueError(
                f"Invalid task status: {status}"
            )

        payload: dict[str, Any] = {
            "status": status,
        }

        if error_message is not None:
            payload["error_message"] = error_message

        response = (
            self.database
            .table(self.TABLE)
            .update(payload)
            .eq("id", task_id)
            .execute()
        )

        return (
            response.data[0]
            if response.data
            else None
        )

    def update(
        self,
        task_id: str,
        data: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Update task."""

        if not task_id:
            raise ValueError(
                "task_id is required."
            )

        if not data:
            raise ValueError(
                "Update data cannot be empty."
            )

        response = (
            self.database
            .table(self.TABLE)
            .update(data)
            .eq("id", task_id)
            .execute()
        )

        return (
            response.data[0]
            if response.data
            else None
        )

    def list_for_user(
        self,
        user_id: str,
        status: str | None = None,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """List tasks for a user."""

        if not user_id:
            raise ValueError(
                "user_id is required."
            )

        if limit < 1:
            raise ValueError(
                "limit must be greater than 0."
            )

        if status is not None and status not in self.VALID_STATUSES:
            raise ValueError(
                f"Invalid task status: {status}"
            )

        query = (
            self.database
            .table(self.TABLE)
            .select("*")
            .eq("user_id", user_id)
        )

        if status:
            query = query.eq(
                "status",
                status,
            )

        response = (
            query
            .order(
                "created_at",
                desc=True,
            )
            .limit(limit)
            .execute()
        )

        return response.data or []
