"""
Verification repository.

Stores verification results generated by the verification engine.
"""

from __future__ import annotations

from typing import Any

from backend.app.database.client import (
    SupabaseDatabase,
    get_database,
)


class VerificationRepository:
    """Database operations for verification results."""

    TABLE = "verification"

    VALID_STATUSES = {
        "pending",
        "verified",
        "mismatch",
        "failed",
        "ineligible",
        "manual_review",
    }

    def __init__(
        self,
        database: SupabaseDatabase | None = None,
    ):
        self.database = database or get_database()

    def create(
        self,
        user_id: str,
        status: str,
        verification_type: str,
        document_id: str | None = None,
        application_id: str | None = None,
        score: float | None = None,
        details: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create a verification record."""

        if not user_id:
            raise ValueError(
                "user_id is required."
            )

        if not verification_type:
            raise ValueError(
                "verification_type is required."
            )

        if status not in self.VALID_STATUSES:
            raise ValueError(
                f"Invalid verification status: {status}"
            )

        payload: dict[str, Any] = {
            "user_id": user_id,
            "status": status,
            "verification_type": verification_type,
        }

        if document_id:
            payload["document_id"] = document_id

        if application_id:
            payload["application_id"] = application_id

        if score is not None:
            payload["score"] = max(
                0.0,
                min(1.0, float(score)),
            )

        if details is not None:
            payload["details"] = details

        response = (
            self.database
            .table(self.TABLE)
            .insert(payload)
            .execute()
        )

        if not response.data:
            raise RuntimeError(
                "Failed to create verification record."
            )

        return response.data[0]

    def get(
        self,
        verification_id: str,
    ) -> dict[str, Any] | None:
        """Get verification result."""

        if not verification_id:
            raise ValueError(
                "verification_id is required."
            )

        response = (
            self.database
            .table(self.TABLE)
            .select("*")
            .eq(
                "id",
                verification_id,
            )
            .limit(1)
            .execute()
        )

        return (
            response.data[0]
            if response.data
            else None
        )

    def list_for_user(
        self,
        user_id: str,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """List verification records for a user."""

        if not user_id:
            raise ValueError(
                "user_id is required."
            )

        if limit < 1:
            raise ValueError(
                "limit must be greater than 0."
            )

        response = (
            self.database
            .table(self.TABLE)
            .select("*")
            .eq(
                "user_id",
                user_id,
            )
            .order(
                "created_at",
                desc=True,
            )
            .limit(limit)
            .execute()
        )

        return response.data or []

    def list_for_document(
        self,
        document_id: str,
    ) -> list[dict[str, Any]]:
        """List verification records for a document."""

        if not document_id:
            raise ValueError(
                "document_id is required."
            )

        response = (
            self.database
            .table(self.TABLE)
            .select("*")
            .eq(
                "document_id",
                document_id,
            )
            .order(
                "created_at",
                desc=True,
            )
            .execute()
        )

        return response.data or []

    def update(
        self,
        verification_id: str,
        data: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Update a verification result."""

        if not verification_id:
            raise ValueError(
                "verification_id is required."
            )

        if not data:
            raise ValueError(
                "Update data cannot be empty."
            )

        response = (
            self.database
            .table(self.TABLE)
            .update(data)
            .eq(
                "id",
                verification_id,
            )
            .execute()
        )

        return (
            response.data[0]
            if response.data
            else None
        )

    def delete(
        self,
        verification_id: str,
    ) -> bool:
        """Delete a verification record."""

        if not verification_id:
            raise ValueError(
                "verification_id is required."
            )

        response = (
            self.database
            .table(self.TABLE)
            .delete()
            .eq(
                "id",
                verification_id,
            )
            .execute()
        )

        return bool(response.data)